:tada: :hammer: Make github command add labels and assignees to pullRequest + Format assignees and labels fields

diff --git a/src/git-hmr b/src/git-hmr
--- a/src/git-hmr
+++ b/src/git-hmr
@@ -13,49 +13,73 @@ assignees="${9}"
 
 if [[ -z "${username}" || -z "${owner}" || -z "${repo}" || -z "${headBranch}" || -z "${baseBranch}" ]]; then
     errorDetails="{headBranch=${headBranch}, baseBranch=${baseBranch}, owner=${owner},repo=${repo}, username=${username}}"
-    printf "🚨 Error! {headBranch, baseBranch, owner, repo} are required! 🚨\n"
-    printf "👉 ${errorDetails}\n"
+    printf "\n🚨 Error! {headBranch, baseBranch, owner, repo} are required! 🚨\n"
+    printf "\n👉 ${errorDetails}\n"
     exit 1
 fi
+
+# format labels and assignees fields, to be accepted json arrays
+labels="\"${labels//,/\",\"}\""
+assignees="\"${assignees//,/\",\"}\""
 
 body="{
     \"head\":\"${headBranch}\",
     \"base\":\"${baseBranch}\",
     \"title\":\"${title}\",
     \"draft\":${isDraft},
-    \"labels\":\"[${labels}]\",
-    \"assignees\":\"[${assignees}]\"
+    \"labels\":[${labels}],
+    \"assignees\":[${assignees}]
 }"
 
 printf "${body}\n"
-read -p "?Create pull request of [${headBranch}] by [${baseBranch}]? y/n:" response
+read -p "?Create pull request of [${headBranch}] by [${baseBranch}]? y/n: " response
 
 case "${response}" in
     y|Y)
     pullsUrl="https://api.github.com/repos/${owner}/${repo}/pulls"
+    issuesUrl="https://api.github.com/repos/${owner}/${repo}/issues"
 
-    erros=`curl -s -o \
+    printf "\n==> Create new pull request..."
+    errors=`curl -s -o \
         -X POST \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: token ${accessToken}" \
         ${pullsUrl} \
         -d "${body}" | jq .errors[0].message`
 
-    if [[ "${erros}" != "null" ]]; then
+
+    if [[ "${errors}" != "null" ]]; then
         printf "\n🚨 Error! Failed to create pull request! 🚨\n"
-        printf "${erros}\n"
+        printf "${errors}\n"
         exit 1
     fi
 
-    pullId=`curl -S -H "Accept: application/vnd.github.v3+json" "${pullsUrl}?status=open&head=${headBranch}" | jq .[0].number`
-    pullUrl="${pullsUrl}/${pullId}"
+    sleep 5s
+
+    printf "Done.\n==> Get pull request id..."
+    pullId=`curl -s -o -H "Accept: application/vnd.github.v3+json" "${pullsUrl}?status=open&head=${headBranch}" | jq .[0].number`
+    pullUrl="https://github.com/${owner}/${repo}/pull/${pullId}"
 
     if [[ "${pullId}" == "null" ]]; then
-        printf "\n🚨 Error! Failed to get pull request: [${pullId}]! 🚨\n"
+        printf "\n🚨 Error! Failed to get pull request: [${pullId}]! After waiting for 5 seconds. 🚨\n"
         exit 1
     fi
 
-    printf "\n🎉🎉🎉 Success! pull request [${pullId}] is created successfully.\n"
+    printf "Done.\n==> Set labels and assignees..."
+    errors=`curl -s -o \
+        -X PATCH \
+        -H "Accept: application/vnd.github.v3+json" \
+        -H "Authorization: token ${accessToken}" \
+        ${issuesUrl}/${pullId} \
+        -d "${body}" | jq .errors[0].message`
+
+    if [[ "${errors}" != "null" ]]; then
+        printf "\n🚨 Error! Failed to set (labels) and (assignees) fields into pull request: [${pullId}]! 🚨\n"
+        printf "${errors}\n"
+        exit 1
+    fi
+
+    printf "Done.\n🎉🎉🎉 Success! pull request [${pullId}] is created successfully.\n"
     if [[ ! -z "${isDockerContainer}" ]]; then printf "visit: ${pullUrl}\n"; else xdg-open "${pullUrl}"; fi
     exit 0
     ;; 
